export const ADD_CART_TO_DECK = 'ADD_CART_TO_DECK'
export const ALL_TO_ALL_DECK_QUEST = 'ALL_TO_ALL_DECK_QUEST'
export const ALL_TO_ALL_DECK_PLAYER = 'ALL_TO_ALL_DECK_PLAYER'
export const ALL_TO_DECK_QUEST = 'ALL_TO_DECK_QUEST'
export const ALL_TO_OUT_DECK_QUEST = 'ALL_TO_OUT_DECK_QUEST'
export const ALL_TO_DECK_PLAYER = 'ALL_TO_DECK_PLAYER'
export const ALL_TO_OUT_DECK_PLAYER = 'ALL_TO_OUT_DECK_PLAYER'
export const ALL_TO_HERO_DECK_PLAYER = 'ALL_TO_HERO_DECK_PLAYER'
export const ALL_TO_MA_PLAYER = 'ALL_TO_MA_PLAYER'
export const ALL_TO_QUEST_DECK = 'ALL_TO_QUEST_DECK'
export const ALL_TO_PREPARACIO_DECK = 'ALL_TO_PREPARACIO_DECK'

export const ONE_TO_PREPARACIO = 'ONE_TO_PREPARACIO'
export const ALL_TO_TAULA = 'ALL_TO_TAULA'

export const SET_LUPA_CARD = 'SET_LUPA_CARD'
export const SET_LUPA_POSITION = 'SET_LUPA_POSITION'


export const PLAYER = 'PLAYER'
export const QUEST = 'QUEST'